#!/usr/bin/env python3
"""Demo-only seed script for the Training Data tab.

Rates any of the seller's own sent emails that don't have feedback yet, then
adds a batch of additional realistic sent+rated emails pulled from the real
account book (real names, industries, plays, signals — bodies generated by
the same deterministic email writer the app falls back to when watsonx is
unavailable), spread across industries and rating levels.

Every seeded/rated email is backdated ~18 days so its mock Salesloft
engagement (opens/clicks/replies) has fully resolved by "today" — otherwise
you'd have to wait real demo-days for opens/replies to show up. This is a
demo convenience only: engagement for anything sent through the app normally
from here on still reveals itself over real elapsed days, same as before.

Usage:
    python3 scripts/seed_training_data.py

Safe to re-run — it only rates emails that don't already have feedback, and
only adds new emails for accounts that don't already have one.
"""
from __future__ import annotations

import random
import sys
from datetime import timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import bobbee
from bobbee.api.accounts import _deterministic_email
from bobbee.api.helpers import services
from bobbee.domain.time import today
from bobbee.services.queries import AccountQueries

BACKDATE_DAYS = 18  # longer than mock engagement's ~7-day max reveal window
STEPS = ["Intro email", "Value follow-up", "Case-study share", "Break-up email"]
FIRST_NAMES = ["Jordan", "Alex", "Sam", "Taylor", "Casey", "Morgan", "Riley", "Devon"]
LAST_NAMES = ["Lee", "Patel", "Garcia", "Kim", "Chen", "Novak", "Ibrahim", "Reyes"]
TITLES = ["CIO", "VP Infrastructure", "Director of IT", "CTO", "Head of Platform Engineering"]
NOTES = [
    "Loved the specific number up front.", "Felt very tailored, not templated.",
    "Great hook, kept it tight.", "", "", "Strong CTA, easy to say yes to.",
    "Nice use of the recent signal.", "", "A little long but the offer landed.",
]


def _rating(rng: random.Random) -> dict:
    """Mostly strong, with enough spread that scores land across
    Good / High Priority / Top Example once engagement is added in."""
    base = rng.choice([5, 5, 5, 4, 4, 3])
    def jitter():
        return max(1, min(5, base + rng.choice([-1, 0, 0, 0, 1])))
    return {"relevance": jitter(), "personalization": jitter(), "clarity": jitter(),
            "cta_strength": jitter(), "tone": jitter()}


def _backdate(svc, email_id: str, sent_date_iso: str) -> None:
    def change(state):
        for record in state.get("emails") or []:
            if record["id"] == email_id:
                record["sent_date"] = sent_date_iso
    svc.repository.update(change)


def main() -> None:
    app = bobbee.create_app()
    with app.app_context():
        svc = services().emails
        queries = AccountQueries(services().repository)
        rng = random.Random("bobbee-seed")
        sent_date_iso = (today() - timedelta(days=BACKDATE_DAYS)).isoformat()

        state = services().repository.load()
        accounts = {a["name"]: a for a in state.get("accounts") or []}

        # 1) Rate the seller's own real sends that don't have feedback yet.
        rated_existing = 0
        for record in state.get("emails") or []:
            if record.get("feedback"):
                continue
            svc.submit_feedback(record["id"], _rating(rng), rng.choice(NOTES))
            _backdate(svc, record["id"], sent_date_iso)
            rated_existing += 1

        # 2) Add new sent+rated emails from real accounts, spread across
        #    industries (up to 2 per industry, ~16 total) that don't already
        #    have a seeded email.
        state = services().repository.load()
        already = {r["account"] for r in (state.get("emails") or [])}
        candidates = [a for a in accounts.values() if a["name"] not in already and a.get("industry")]
        rng.shuffle(candidates)

        by_industry: dict[str, int] = {}
        picked = []
        for account in candidates:
            industry = account["industry"]
            if by_industry.get(industry, 0) >= 2:
                continue
            by_industry[industry] = by_industry.get(industry, 0) + 1
            picked.append(account)
            if len(picked) >= 16:
                break

        added = 0
        for account in picked:
            step = rng.choice(STEPS)
            context, _ = queries.brief_context(account["name"])
            first = rng.choice(FIRST_NAMES)
            context.update(contact_first_name=first, email_step=step)
            draft = _deterministic_email(account["name"], first, step, context)

            record = svc.record_sent(
                account=account["name"], industry=account.get("industry"),
                tier=account.get("tier"), play=account.get("play"),
                contact_first=first, contact_last=rng.choice(LAST_NAMES),
                contact_title=rng.choice(TITLES),
                cadence=account.get("cadence") or "US | Select | Infrastructure Outbound",
                step=step, subject=draft["subject"], body=draft["body"], source="deterministic",
            )
            svc.submit_feedback(record["id"], _rating(rng), rng.choice(NOTES))
            _backdate(svc, record["id"], sent_date_iso)
            added += 1

        print(f"Rated {rated_existing} existing sent email(s).")
        print(f"Added and rated {added} new example(s) across {len(by_industry)} industries.")

        report = svc.training_data()
        tiers: dict[str, int] = {}
        for row in report["examples"]:
            label = ("Top Example" if "Top Example" in row["badges"]
                      else "High Priority" if "High Priority" in row["badges"] else "Good Example")
            tiers[label] = tiers.get(label, 0) + 1
        print(f"Training Data tab now shows {report['count']} qualifying example(s): {tiers}")


if __name__ == "__main__":
    main()
